name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore
      
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal

    - name: Publish
      run: |
        mkdir blocks
        dotnet publish ./App/App.csproj -c Release -o blocks/win-x64 -r win-x64 --self-contained true /p:PublishReadyToRun=true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
        dotnet publish ./App/App.csproj -c Release -o blocks/win-x86 -r win-x86 --self-contained true /p:PublishReadyToRun=true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
    - name: zip win artifact
      run: |
        powershell Compress-Archive -Path ./blocks/* -DestinationPath ./blocks-win.zip
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Windows
        path: ./blocks-win.zip
